"----------------------------------------
"
" Author        :   Lasercata
" Last update   :   2023.04.14
" Version       :   v3.13.4
"
"----------------------------------------

"---Tabulations
set tabstop=4       " number of visual spaces per tab
set softtabstop=4   " number of spaces in tab when editing
set shiftwidth=4    " number of spaces to use for auto indent
set expandtab       " tabs are space
set autoindent
set copyindent      " copy indent from the previous line

set breakindent     "Add indentation to wrapped lines.

"---Syntax
filetype plugin indent on "Enable file type detection, indent for the detected file type, and use the plugin for it.
syntax enable             "Enable syntax highlighting
set background=dark

"---Appearance
set nu     "Line numbers
set ruler  "Show things at bottom right
set nolist "Don't show '$' at the end of lines
set mouse=r
set scrolloff=3

"---Search
set incsearch  "Search as char entered
set hlsearch   "Highlight matches
set ignorecase "Ignore the case of normal letters in search
set smartcase  "Overwrite ignorecase if there is an uppercase character in the searched text

"---Spelling
setlocal spell
set spelllang=en_us,fr

" Correct the closer error behind cursor in insert mode.
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

" Toggle spell in normal mode
nnoremap <C-s> :set invspell<CR>

"---Mappings
"-Leader keys
let mapleader = " "
let maplocalleader = ","

"-Escape from insert mode
inoremap jk <esc>
inoremap kj <esc>

"-Also from terminal
"tnoremap jk <C-\><C-n>
"tnoremap kj <C-\><C-n>
tnoremap <ESC> <C-\><C-n>

"-Deleting in insert mode (with C-h, C-w) starts a new undo sequence
inoremap <C-h> <C-g>u<C-h>
inoremap <C-w> <C-g>u<C-w>

"-Auto close delimiters (now using pear-tree extension)
"inoremap " ""<left>
"inoremap ' ''<left>
"inoremap ( ()<left>
"inoremap [ []<left>
"inoremap { {}<left>
"inoremap {<CR> {<CR>}<ESC>O

"-Wrap selection with a delimiter (in visual mode)
vnoremap ( <ESC>`>a)<ESC>`<i(<ESC>%
vnoremap [ <ESC>`>a]<ESC>`<i[<ESC>%
vnoremap { <ESC>`>a}<ESC>`<i{<ESC>%

"-Deleting surrounding delimiter (any that is detected with %) in normal mode.
"The cursor can be anywhere inside the delimiter pair.
nnoremap <leader>ds %v%<ESC>x`<x`>

"-Change window
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-h> <C-w>h

"Also from terminal
tnoremap <C-j> <C-\><C-n><C-w>j
tnoremap <C-k> <C-\><C-n><C-w>k
tnoremap <C-l> <C-\><C-n><C-w>l
tnoremap <C-h> <C-\><C-n><C-w>h

"-Change buffer faster
nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>

"-Move cursor in insert and command mode : Alt + [hjkl$_]
inoremap <M-j> <Down>
inoremap <M-k> <Up>
inoremap <M-l> <Right>
inoremap <M-h> <Left>
inoremap <M-$> <End>
inoremap <M-_> <Home>

cnoremap <M-j> <Down>
cnoremap <M-k> <Up>
cnoremap <M-l> <Right>
cnoremap <M-h> <Left>
cnoremap <M-$> <End>
cnoremap <M-_> <Home>

"-In visual mode, <leader>i indents selection, <leader>I decrease indentation, and both reselect the selection
vnoremap <leader>i >gv
vnoremap <leader>I <gv

"Also from normal mode
nnoremap <leader>i >>
nnoremap <leader>I <<


"---Plugins
call plug#begin('~/.config/nvim/plugged')

"-UltiSnips snippets
Plug 'sirver/ultisnips'
    let g:UltiSnipsExpandTrigger = '<tab>'
    let g:UltiSnipsJumpForwardTrigger = '<tab>'
    let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
    "let g:UltiSnipsSnippetDirectories = '~/.config/nvim/my_snippets/UltiSnips'
    let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"]

"-Vimtex
Plug 'lervag/vimtex'
    let g:vimtex_view_method = 'zathura'

"-Vim-Slime (for ocaml)
"Plug 'jpalardy/vim-slime'
    "let g:slime_target = "tmux"
    "let g:slime_paste_file = "$HOME/.slime_paste"

"-Nerd tree
Plug 'scrooloose/nerdtree'
    "let NERDTreeShowHidden=1
    nnoremap <C-t> :NERDTreeToggle<CR>
    "autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif


"-Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts = 1

"-Tmuxline
Plug 'edkolev/tmuxline.vim'
    let g:airline#extensions#tmuxline#enabled = 1
    let airline#extensions#tmuxline#snapshot_file = "~/.tmux-status.conf"

"-Pear-tree
Plug 'tmsvg/pear-tree'
    let g:pear_tree_smart_openers = 1
    let g:pear_tree_smart_closers = 1
    let g:pear_tree_smart_backspace = 1
    let g:pear_tree_repeatable_expand = 0

"-Tagbar: a class outline viewer for Vim
Plug 'preservim/tagbar'
    nnoremap <leader>o :TagbarToggle<CR>

"-Catppuccin colorscheme
Plug 'catppuccin/nvim', { 'as': 'catppuccin' }

"-Nightfly colorscheme
Plug 'bluz71/vim-nightfly-colors', { 'as': 'nightfly' }
    let g:nightflyTransparent= v:true

"-Moonfly
Plug 'bluz71/vim-moonfly-colors', { 'as': 'moonfly' }

call plug#end()

"---Apply theme
colorscheme nightfly
