#--------------------------------
#
# Author            : Lasercata
# Last modification : 2023.04.14
# Version           : v1.0
#
#--------------------------------

alias _='sudo'
alias _i='sudo -i'

alias ll='ls -lh'
alias la='ls -lha'
alias l='ls -CF'

alias dd='dd status=progress'

alias p3='python3'
alias p='python'

alias viqt='nvim-qt'

#When quitting ranger, the terminal will cd to the last location.
alias rg='. ranger'
